export * from './UrlBase'
export * from './GetMovie'
export * from './GetGenre'
export * from './GetAuthor'
export * from './PostMovie'
export * from './UpdateMovie'
export * from './PostAuthor'
export * from './PostGenre'
