export * from "./URLbaseNG"
export * from "./movie.model"
export * from "./returnLogin"
export * from "./moviehttp.model"
export * from './returnLogin2'
export * from './genreDesc'
export * from './authorName'
export * from './authorRes'
export * from './createMovie'
export * from './MovieResCreate'
export * from './genreREs'
