export interface MovieResCreate{

    movieAuthor: string,
    title: string,
    genreDescription: string,
    genreid: string,
    authorid: string,
    releaseDate: string,
    authorName: string,
    price: string,
    rating: string,
    runtimeMins: string,
    plot: string,
    writers: string,
    stars: string,
    countries: string,
    languages: string,
    idImdb: string,
    awards: string,
    linkEmbed: string,
    videoDescription: string,
    linkPoster1: string,
    linkPoster2: string,
    image1: string,
    image2: string,
    lastModificationTime: string,
    lastModifierId: string,
    creationTime: string,
    creatorId: string,
    id: string,

}
